[build-system]
requires = ["uv_build>=0.12.4,<0.13"]
build-backend = "uv_build"

[project]
name = "edwh-pipcompile-plugin"
description = 'Plugin that integrates `pip-tools` with `edwh`'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Robin van der Noord", email = "robin.vdn@educationwarehouse.nl" },
  { name = "Remco Boerma", email = "remco.b@educationwarehouse.nl" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  'edwh>=0.19',
  # "pip-tools",
  "uv",
  "tomli",
  "typing_extensions",
]
version = "0.6.2"

[tool.edwh.pipcompile.__cwd__]
input = ["include.in"]
output = "incl.txt"

[tool.edwh.pipcompile.demo]
input = ["a.in", "b.in"]
output = "c.out"

[project.optional-dependencies]
dev = [
  "edwh",
]

[project.urls]
Documentation = "https://github.com/educationwarehouse/edwh-pipcompile-plugin#readme"
Issues = "https://github.com/educationwarehouse/edwh-pipcompile-plugin/issues"
Source = "https://github.com/educationwarehouse/edwh-pipcompile-plugin"

# https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/#using-package-metadata
[project.entry-points."edwh.tasks"]
pip = "edwh_pipcompile_plugin.pipcompile_plugin"

[tool.vommit]
allow_breaking_bang = true
allow_breaking_footer = true
prerelease_token = "beta"
confirm = true
ignore = []

[tool.vommit.git]
enabled = true
origin = "origin"
branch = "master"
on_wrong_branch = "error"
tag_format = "v{version}"
commit_format = "{version}"

[tool.vommit.changelog]
enabled = true
file = "CHANGELOG.md"
include_prereleases = false
placeholder = "<!--next-version-placeholder-->"
placeholder_regex = "<auto>"
entry_title_format = "## v{version} ({date:%Y-%m-%d})"

[tool.vommit.changelog.levels]
feat = "Feature{s}"
fix = "Fix{es}"
break = "Breaking Change{s}"
docs = "Documentation"
perf = "Performance"

[tool.vommit.pypi]
enabled = true
use_keyring = true

[tool.vommit.commands]
clean = "rm -rf ./dist"
build = "uv build"
publish = "uv publish"
post_publish = ""

[tool.vommit.version_bump_map]
break = "major"
build = "patch"
chore = "patch"
feat = "minor"
fix = "patch"
perf = "patch"
refactor = "patch"

[tool.hatch.envs.default]
dependencies = []

[tool.hatch.envs.default.scripts]
publish = [
  'semantic-release publish',
  'hatch build -c',
  'hatch publish',
]

test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
]

[[tool.hatch.envs.all.matrix]]
python = ["3.10", "3.11", "3.12", "3.14"]

[tool.hatch.envs.lint]
detached = true
dependencies = [
  "black>=23.1.0",
  "mypy>=1.0.0",
  "ruff>=0.0.243",
]
[tool.hatch.envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:src/edwh_pipcompile_plugin tests}"
style = [
  "ruff {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "ruff --fix {args:.}",
  "style",
]
all = [
  "style",
  "typing",
]

[tool.black]
target-version = ["py310"]
line-length = 120
skip-string-normalization = false

[tool.isort]
profile = "black"

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = [
    "F", # pyflake error
    "E", # pycodestyle error
    "W", # pycodestyle warning
    "Q", # quotes
    "A", # builtins
    # "C4", # comprehensions - NO: doesn't allow dict()
    # "RET", # return - NO: annoying
    "SIM", # simplify
    "ARG", # unused arguments
    # "COM", # comma's - NO: annoying
    # "PTH", # use pathlib - NO: annoying
    "RUF", # ruff rules
]

ignore = [
  # Allow non-abstract empty methods in abstract base classes
  "B027",
  # Allow boolean positional values in function calls, like `dict.get(... True)`
  "FBT003",
  # Ignore checks for possible passwords
  "S105", "S106", "S107",
  # Ignore complexity
  "C901", "PLR0911", "PLR0912", "PLR0913", "PLR0915",
]
unfixable = [
  # Don't touch unused imports
  "F401",
]

[tool.su6]
directory = "src"

[tool.ruff.lint.isort]
known-first-party = ["edwh_pipcompile_plugin"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**/*" = ["PLR2004", "S101", "TID252"]

[tool.coverage.run]
source_pkgs = ["edwh_pipcompile_plugin", "tests"]
branch = true
parallel = true
omit = [
  "src/edwh_pipcompile_plugin/__about__.py",
]

[tool.coverage.paths]
edwh_pipcompile_plugin = ["src/edwh_pipcompile_plugin", "*/edwh-pipcompile-plugin/src/edwh_pipcompile_plugin"]
tests = ["tests", "*/edwh-pipcompile-plugin/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
